- name: "Copy config files"
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: '../files/run-config.sh', dest: '/home/ansible/job/run-config.sh', owner: 'root', group: 'root', mode: '0755' }

- cron:
    name: "Cron at reboot"
    special_time: reboot
    job: "/home/ansible/job/run-config.sh"