- name: 'edit config files for security and compression'
  command: "{{ item }}"
  become: true
  become_method: sudo
  with_items:
    - sed -i 's:;cgi.fix_pathinfo=1:cgi.fix_pathinfo=0:g' /etc/php/7.0/fpm/php.ini
    - rm -rf /var/www/html
    - sed -i 's:# gzip_vary:gzip_vary:g' /etc/nginx/nginx.conf
    - sed -i 's:# gzip_proxied:gzip_proxied:g' /etc/nginx/nginx.conf
    - sed -i 's:# gzip_comp_level:gzip_comp_level:g' /etc/nginx/nginx.conf
    - sed -i 's:# gzip_buffers:gzip_buffers:g' /etc/nginx/nginx.conf
    - sed -i 's:# gzip_http_version:gzip_http_version:g' /etc/nginx/nginx.conf
    - sed -i 's:# gzip_min_length:gzip_min_length:g' /etc/nginx/nginx.conf
    - sed -i 's:# gzip_types:gzip_types:g' /etc/nginx/nginx.conf
  notify:
    - stop services

- name: "Delete /var/www/html folder"
  become: true
  become_method: sudo
  shell: /bin/rm -rf /var/www/html/