- name: "stop services"
  service: >
    name="{{ item }}"
    state=stopped
  with_items:
    - nginx
    - php7.0-fpm
  notify:
    - start services


- name: "start services"
  service: >
    name="{{ item }}"
    state=started
  with_items:
    - nginx
    - php7.0-fpm